exp_name: dqn_g_handcraft
use_wandb: False
model_name: dqn_g_handcraft
length: 4
lr: 1e-3
num_episodes: 30000
hidden_dim: 128
gamma: 0.99
# epsilon: 0.01
# target_update: 10
target_update: 50
buffer_size: 10000
batch_size: 64
model_save_dir: save_model
max_steps: 100
eval: False
log_frequency: 500
minimal_size: 64
env_reward_type: euclidean
policy_type: goal
minimal_epsilon: 0.1
epsilon: 0.9
delta_epsilon: 0.00001

reward_success: 0
reward_fail: -1

step_is_fast: false