exp_name: caogao
use_wandb: True
model_name: dqn
length: 4
lr: 1e-3
num_episodes: 500
hidden_dim: 128
gamma: 0.99
epsilon: 0.01
target_update: 10
buffer_size: 10000
batch_size: 64
model_save_dir: save_model